using System.Collections;
using UnityEngine;

public class NormalBody : MonoBehaviour, BodyController
{
    // ‘ج‚جڈî•ٌ
    [SerializeField] public BodyData bodyData;

    [Header("“ھ‚ةکA“®‚·‚éRig‚ًژw’è")]
    [SerializeField] public GameObject BodyToHeadRig = null;
    [Header("‘«‚ةکA“®‚·‚éRig‚ًژw’è")]
    [SerializeField] public GameObject BodyToLegRig = null;

    public GameObject LegToBodyRig = null;

    [SerializeField] private Collider robotAttackRangeA;
    [SerializeField] private Collider robotAttackRangeB;

    //SEٹضکA
    [Header("SE‚ًژw’è‚µ‚ـ‚·پB")]
    [SerializeField]
    public AudioSource audioSource;

    float lapseTime;

    public bool isAttackable;

    //–،•û‚©‚ؤ‚«‚©true‚ب‚çƒvƒŒƒCƒ„پ[‚ئ–،•û‚ًچUŒ‚‚·‚éپB
    public bool isEnemy = false;

    public RobotAction robotAction;

    private Animator animator;

    private Rigidbody rb;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Awake()
    {
        animator = transform.GetChild(0).GetComponent<Animator>();
        rb = GetComponent<Rigidbody>();

        isAttackable = true;
        robotAttackRangeA.enabled = false;
        robotAttackRangeB.enabled = false;

        lapseTime = 0.0f;

        robotAction = this.GetComponentInParent<RobotAction>();
        if (robotAction == null)
        {
            return;
        }
    }

    // Update is called once per frame
    void Update()
    {
        if (robotAction.IsSet)
        {
            if (LegToBodyRig)
            {
                BodyToLegRig.transform.position = LegToBodyRig.transform.position;
            }

            animator.SetBool("Walk", true);
        }

        // چUŒ‚‚جƒNپ[ƒ‹ƒ^ƒCƒ€
        // isAttackable‚ھfalse‚ب‚çپA’¼‘O‚جƒtƒŒپ[ƒ€‚©‚ç‚جŒo‰كژ‍ٹش‚ً‘«‚·
        if (!isAttackable)
        {
            lapseTime += Time.deltaTime;

            //lapsetime‚ھƒNپ[ƒ‹ƒ^ƒCƒ€‚ً‰z‚¦‚½‚çپAisAttackable‚ًtrue‚ة–ك‚µ‚ؤ
            //ژں‚ة”ُ‚¦‚ؤپAlapseTime‚ً0‚إڈ‰ٹْ‰»
            if (lapseTime >= bodyData.coolTimeA && lapseTime >= bodyData.coolTimeB)
            {
                isAttackable = true;
                lapseTime = 0.0f;
            }
        }
    }

    public void CreateSetup()
    {
        this.transform.GetComponentInChildren<SkinnedMeshRenderer>().material = bodyData.material;
        audioSource = this.GetComponentInParent<AudioSource>();
    }

    public void PartsDestroy(bool isSet)
    {
        if (isSet)
        {
            rb.useGravity = false;
            rb.isKinematic = true;
        }
        else
        {
            rb.useGravity = true;
            rb.isKinematic = false;
        }
    }

    public int GetDamageA()
    {
        return bodyData.damageA;
    }

    public int GetDamageB()
    {
        return bodyData.damageB;
    }

    public BodyData OutputData()
    {
        return bodyData;
    }

    public void Attack()
    {
        //چUŒ‚’†‚©پAƒNپ[ƒ‹ƒ^ƒCƒ€’†‚ب‚ç•ش‚·پB
        if (!isAttackable)
        {
            return;
        }
        //ˆل‚¤‚ب‚çچUŒ‚’†‚ًtrue‚ة‚µ‚ؤڈˆ—‌‚ًژہچs
        else
        {
            int rand = UnityEngine.Random.Range(1, 11);

            //ٹm—¦‚إچUŒ‚‚ھ•د‚ي‚éپB
            if (rand >= 4)
            {
                animator.SetTrigger("Punch");
                StartCoroutine(Attack(bodyData.preparationTimeA, bodyData.occurrenceTimeA, bodyData.finishTimeA, 0));
            }
            if (rand <= 3)
            {
                animator.SetTrigger("Rariat");
                StartCoroutine(Attack(bodyData.preparationTimeB, bodyData.occurrenceTimeB, bodyData.finishTimeB, 1));
            }

            isAttackable = false;
        }
    }

    IEnumerator Attack(float preparationTime, float occurrenceTime, float finishTime, int AttackType)
    {
        if (AttackType == 0)
        {
            //ڈ€”ُژ‍ٹش‚ـ‚إ‘ز‚آ
            yield return new WaitForSeconds(preparationTime);
            //robotAttackPunch.OnCollider();
            robotAttackRangeA.enabled = true;
            if (audioSource)
            {
                audioSource.PlayOneShot(bodyData.attackSoundA);
            }

            yield return new WaitForSeconds(occurrenceTime);
            robotAttackRangeA.enabled = false;
            //robotAttackPunch.OffCollider();
            yield return new WaitForSeconds(finishTime);
        }
        else if (AttackType == 1)
        {
            //ڈ€”ُژ‍ٹش‚ـ‚إ‘ز‚آ
            yield return new WaitForSeconds(preparationTime);
            //robotAttackRariat.OnCollider();
            robotAttackRangeB.enabled = true;
            if (audioSource)
            {
                audioSource.PlayOneShot(bodyData.attackSoundB);
            }

            yield return new WaitForSeconds(occurrenceTime);
            //robotAttackRariat.OffCollider();
            robotAttackRangeB.enabled = false;
            yield return new WaitForSeconds(finishTime);
        }
        robotAction.robotState = RobotAction.RobotState.Idle;
    }
}
